all:
  children:
    iscsi:
      hosts:

    jumpboxes_windows:
      hosts:

    jumpboxes_linux:
      hosts:
        40.68.46.207:
          ansible_connection:  "ssh"
          ansible_user:        "bdelangh"

    hanadbnodes:
      hosts:
        13.95.69.233:
          ansible_connection:  "ssh"
          ansible_user:        "bdelangh"

    # Groups below are collections of the above groups for easier reference
    all_jumpboxes:
      children:
        jumpboxes_windows:
        jumpboxes_linux:

    all_linux_servers:
      children:
        jumpboxes_linux:
        hanadbnodes:
        scs:
        app:

    # Localhost provisioning
    local:
      hosts:
        localhost:
          ansible_connection: "local"
          ansible_user:       "azureadm"
